### PR TITLE
javascript: replace exceptions with SWIG_exit

### LINKED ISSUE #1858: SWIG host tool cannot be built without C++ exception support
The SWIG core is using exceptions in two places:

Source/Modules/javascript.cxx:      throw "Illegal state.";
Source/Modules/javascript.cxx:      throw "Illegal state.";

When building for Android as a host tool, C++ exception support is disabled by default. These cases are not obviously good uses of exceptions, as they cannot be handled in a useful way. Also, other parser errors in this file are handled with a printf and SWIG_exit(), which looks reasonable for these cases as well.

### PR DESCRIPTION
**Pull request by adelva1984**
When building SWIG for Android, there is no support for C++ exceptions.

In the cases there is "Illegal state", it seems more like an internal
error, so we can replace the throw calls with a debug print and exit
immediately.

Closes #1858

### CODE REVIEW

File: Source/Modules/javascript.cxx [hunk 1]
```diff
@@ -2212,7 +2213,8 @@ void V8Emitter::marshalInputArgs(Node *n, ParmList *parms, Wrapper *wrapper, Mar
       Printf(arg, "args[%d]", i);
       break;
     default:
-      throw "Illegal state.";
+      Printf(stdout, "Illegal state.");
```
Comment (wsfulton) [inline Source/Modules/javascript.cxx:2216]:
```suggestion
      Printf(stderr, "Illegal MarshallingMode.");
```

File: Source/Modules/javascript.cxx [hunk 2]
```diff
@@ -1575,7 +1575,8 @@ void JSCEmitter::marshalInputArgs(Node *n, ParmList *parms, Wrapper *wrapper, Ma
       Printf(arg, "argv[%d]", i);
       break;
     default:
-      throw "Illegal state.";
+      Printf(stdout, "Illegal state.");
```
Comment (wsfulton) [inline Source/Modules/javascript.cxx:1578]:
```suggestion
      Printf(stderr, "Illegal MarshallingMode.");
```

**Review by wsfulton — CHANGES_REQUESTED** [review]
Please modify patches with the 2 suggestions and I'll merge it in. Thanks.
